/* generated by unplugin-react-components */
export {}
declare global{
	const App: typeof import('./src/App')['default']
	const MainLayout: typeof import('./src/layouts/MainLayout')['default']
	const AppRoutes: typeof import('./src/router/AppRoutes')['default']
	const Login: typeof import('./src/pages/auth/Login')['default']
}